<!DOCTYPE html>
<html lang="en">

<?php readfile('views/head.phtml'); ?>

<body>

    <?php readfile('views/header.phtml'); ?>

    <main>
        <?php readfile('forms/create-todo-list.phtml'); ?>
        <ul>
        <?php
        foreach ($todoLists as $title) {
            include 'views/todo-list-summary.phtml';
        }
        ?>
        </ul>
        <p class="count">Found <?php echo count($todoLists); ?> lists</p>
    </main>

    <?php readfile('views/footer.phtml'); ?>

</body>

</html>