<!DOCTYPE html>
<html lang="en">

<?php readfile('views/head.phtml'); ?>

<body>

    <?php readfile('views/header.phtml'); ?>

    <main>
        <ul>
            <li class="todo-list">
                <h2 class="title">This is a todo-list</h2>
            </li>
            <li class="todo-list">
                <h2 class="title">This is another todo-list</h2>
            </li>
            <li class="todo-list">
                <h2 class="title">A third todo-list</h2>
            </li>
            <li class="todo-list">
                <h2 class="title">list 4</h2>
            </li>
            <li class="todo-list">
                <h2 class="title">The fifth todo-list</h2>
            </li>
        </ul>
    </main>

    <?php readfile('views/footer.phtml'); ?>

</body>

</html>